### ISSUE TITLE
Skip link

### ISSUE THREAD

**Issue by jeff-cook** [tani/textlint-rule-spelling#7]
Is there an easy way to have textlint-rule-spelling skip spell check on all links? 

## Example
```
![WARNING:](images/warning_25x25_red.svg)
```

**Comment by bibliobibulus** [comment]
Sorry for late reply. The `skipPatterns` accepts regular expressions. Thus, `\\[.*?\\]\\(.*?\\)`.

**Comment by jeff-cook** [comment]
Here are the config and output. 

```yaml
rules:
  spelling:
    skipPatterns:
      - svg
      - \\!\\[.*?\\]\\(.*?\\)
```

```bash
spelling: svg -> avg, sag, SVN, VG
/work/README.md:5:1
       v
    4. 
    5. ![build](../../build/badges/master/pipeline.svg)
    6. 
       ^
```

textlint --version
v11.6.3

"textlint-rule-spelling": "0.1.1"
